== S3
jets3t :http://jets3t.s3.amazonaws.com/downloads.html[http://jets3t.s3.amazonaws.com/downloads.html]s3md : http://s3tools.org/s3cmd[http://s3tools.org/s3cmd]  

== AMI 
이미지 목록 : https://aws.amazon.com/amis/[https://aws.amazon.com/amis/]  

== EC2

http://blog.daum.net/_blog/BlogTypeView.do?blogid=0cBn9&articleno=2&categoryId=5&regdt=20120803125355#ajax_history_home[AWS 인스턴스 성능 분석]  
ec2-run-instancesec2-describe-instancesec2-terminate-instancesec2-add-keypair KEYPAIR_NAME  
ec2-authorize GROUP_NAME [OPTIONS]ec2-authorize default -p 22ec2-add-group GRUP -d DESCRIPTIONec2-allocate-addressec2-associate-address -i i-a7d32cc3 67.202.55.255ec2-describe-addressesec2-create-volume --size SIZE_GB -z ZONEec2-create-volume --size 10 -z us-east-1aec2-describe-volumesec2-attach-volumeec2-detach-volume e2-create-snapshotec2-describe-snapshops  

== RDS
http://aws.amazon.com/ko/rds/[http://aws.amazon.com/ko/rds/]http://aws.amazon.com/ko/running_databases/[http://aws.amazon.com/ko/running_databases/]http://aws.amazon.com/ko/rds/faqs[http://aws.amazon.com/ko/rds/faqs]  

== SQS
http://www.ibm.com/developerworks/kr/library/j-javadev2-17/index.html[http://www.ibm.com/developerworks/kr/library/j-javadev2-17/index.html]  

== ELB
http://blog.daum.net/_blog/BlogTypeView.do?blogid=0cBn9&articleno=3&categoryId=5&regdt=20120803142824#ajax_history_home[아마존(AWS)이 ELB 에 고정 공인IP 를 제공하지 않는 이유?]http://blog.daum.net/_blog/BlogTypeView.do?blogid=0cBn9&articleno=21&categoryId=5&regdt=20120910122524#ajax_history_home[AWS의 ELB와 Netflix의 신작(?) Eureka]  

== EIP
http://blog.daum.net/_blog/BlogTypeView.do?blogid=0cBn9&articleno=19&_bloghome_menu=recentthumb#ajax_history_home[AWS의 EIP(Elastic IP) 가격 정책과 동작 원리]

== VPC
http://blog.daum.net/_blog/BlogTypeView.do?blogid=0cBn9&articleno=18&categoryId=5&regdt=20120821113335#ajax_history_home[아마존 VPC(Virtual Private Cloud) 구성]http://architects.dzone.com/articles/aws-vpc-networking-beginners[http://architects.dzone.com/articles/aws-vpc-networking-beginners]: So, an elastic ip and an igw in the routing table are two criterion for an instance to be available directly from the internet.Subnets with such routing tables attached to them are also known as public subnets (non-local traffic routed to internet gateway  
