http://msdn.microsoft.com/ko-kr/magazine/dd419654.aspx[DDD(Domain Driven Design) 소개]

http://www.infoq.com/minibooks/domain-driven-design-quickly[http://www.infoq.com/minibooks/domain-driven-design-quickly]

http://www.infoq.com/news/2006/12/domain-driven-design[http://www.infoq.com/news/2006/12/domain-driven-design]

http://www.infoq.com/news/2007/09/eric-evans-domain-driven-design[http://www.infoq.com/news/2007/09/eric-evans-domain-driven-design]

 http://www.infoq.com/articles/ddd-in-practice[http://www.infoq.com/articles/ddd-in-practice]

 http://www.infoq.com/presentations/design-strategic-eric-evans[http://www.infoq.com/presentations/design-strategic-eric-evans]

http://www.infoq.com/articles/ddd-in-practice[Domain Driven Design and Development In Practice]

http://www.infoq.com/news/2007/09/eric-evans-domain-driven-design[http:///www.infoq.com/news/2007/09/eric-evans-domain-driven-design]

http://www.slideshare.net/gyumee/ddd-10067384[박성철님의 DDD 산책 발표] :   

http://www.infoq.com/presentations/model-to-work-evans;jsessionid=598EEE33567DCD3CDD6A2D35EA48A71C[DDD: putting the model to work]

http://truthiness.pe.kr/blog/archives/323[나도 DDD 하고싶어 모델링 적용기]

http://toby.epril.com/?p=356[DDD에서 말하는 Ubiquitous Langauge가 어려운 이유]

http://whiteship.tistory.com/1323[Services]

http://whiteship.tistory.com/1325[Modules]

http://whiteship.tistory.com/1341[Factories]

http://younghoe.info/747[DDD 인덱스 페이지]

http://whiteship.tistory.com/2267[DDD 입문에 좋은 글]

http://gyumee.egloos.com/1783716[도메인 로직과 SQL] (원문 : http://martinfowler.com/articles/dblogic.html[Domain Logic and SQL] )

http://www.zdnet.co.kr/builder/dev/web/0,39031700,39170212,00.htm[고객과 개발자를 아우르는 하나의 언어 도메인이 주도하는 개발]

http://www.zdnet.co.kr/builder/dev/web/0%2C39031700%2C39170216%2C00.htm[JSSpec을 이용한 행동 주도 개발 BDD(Behavior Driven Development)]

http://whiteship.me/2268[[DDD] Whiteship's DDD 아키텍처]

http://younghoe.info/1076[데이터 주도 설계 대 책임 주도 설계]

빈약한 Domain Object : http://martinfowler.com.bliki.anemicdomainmodel.html/[http://martinfowler.com.bliki.AnemicDomainModel.html]

http://bcho.tistory.com/356[DDD (Domain Driven Design) - Context Continuous Integration]

http://bcho.tistory.com/360[Domain Driven Design - Modeling]

http://aeternum.egloos.com/1160846[DDD vs Repository]

http://pds17.egloos.com/pds/201003/31/18/Domain-Driven_Design_Essence.pdf[http://pds17.egloos.com/pds/201003/31/18/Domain-Driven_Design_Essence.pdf]

http://smack.kr/372[좋은 도메인 모델은 어떻게 만들 수 있을까? 10가지 최고의 충고.]

http://aeternum.egloos.com/2422827[Domain-Driven Design Essence]

http://aeternum.egloos.com/2628475[Rich Domain Model]

== Sculptor

http://www.theserverside.com/tt/articles/content/ProductivityWithSculptor/article.html[http://www.theserverside.com/tt/articles/content/ProductivityWithSculptor/article.html]

==== Sample

http://dddsample.sourceforge.net/[http://dddsample.sourceforge.net/]

http://dddstepbystep.com/[http://dddstepbystep.com/]

http://debasishg.blogspot.com/2006/12/domain-driven-design-service-injection_12.html[http://debasishg.blogspot.com/2006/12/domain-driven-design-service-injection_12.html]


== 연재

http://aeternum.egloos.com/1747170[유연한 설계를 위한 패턴과 원리 - 1.시간, 돈, 그리고 GENERIC SUBDOMAIN 1부]

http://aeternum.egloos.com/1832181[유연한 설계를 위한 패턴과 원리 - 1.시간, 돈, 그리고 GENERIC SUBDOMAIN 2부]

http://aeternum.egloos.com/1891121[유연한 설계를 위한 패턴과 원리 - 1.시간, 돈, 그리고 GENERIC SUBDOMAIN 3부]

http://aeternum.egloos.com/1899296[유연한 설계를 위한 패턴과 원리 - 1.시간, 돈, 그리고 GENERIC SUBDOMAIN 4부]

http://aeternum.egloos.com/1912820[유연한 설계를 위한 패턴과 원리 - 1.시간, 돈, 그리고 GENERIC SUBDOMAIN 5부]

http://aeternum.egloos.com/1960629[유연한 설계를 위한 패턴과 원리 - 1.시간, 돈, 그리고 GENERIC SUBDOMAIN 6부]

http://aeternum.egloos.com/1960629[유연한 설계를 위한 패턴과 원리 - 1.시간, 돈, 그리고 GENERIC SUBDOMAIN 7부]

http://aeternum.egloos.com/1984703[유연한 설계를 위한 패턴과 원리 - 2.의도를 명확하게 1부]

http://aeternum.egloos.com/1986866[유연한 설계를 위한 패턴과 원리 - 2.의도를 명확하게 2부]

http://aeternum.egloos.com/2150438[유연한 설계를 위한 패턴과 원리 - 2.의도를 명확하게 3부]

http://aeternum.egloos.com/2195758[유연한 설계를 위한 패턴과 원리 - 2.의도를 명확하게 4부]

http://aeternum.egloos.com/2312162[유연한 설계를 위한 패턴과 원리 - 2.의도를 명확하게 5부]

http://aeternum.egloos.com/2322024[유연한 설계를 위한 패턴과 원리 - 2.의도를 명확하게 6부]

http://aeternum.egloos.com/2333979[유연한 설계를 위한 패턴과 원리 - 2.의도를 명확하게 7부]

http://aeternum.egloos.com/2363367[유연한 설계를 위한 패턴과 원리 - 3.리팩토링을 통한 진보 1부]

http://aeternum.egloos.com/2374119[유연한 설계를 위한 패턴과 원리 - 3.리팩토링을 통한 진보 2부]

http://aeternum.egloos.com/2382119[유연한 설계를 위한 패턴과 원리 - 3.리팩토링을 통한 진보 3부]

http://aeternum.egloos.com/2382485[유연한 설계를 위한 패턴과 원리 - 3.리팩토링을 통한 진보 4부]

http://aeternum.egloos.com/2388357[유연한 설계를 위한 패턴과 원리 - 3.리팩토링을 통한 진보 5부]

http://aeternum.egloos.com/2402082[유연한 설계를 위한 패턴과 원리 - 3.리팩토링을 통한 진보 6부]

http://aeternum.egloos.com/2405638[유연한 설계를 위한 패턴과 원리 - 3.리팩토링을 통한 진보 7부]

http://aeternum.egloos.com/2420521[유연한 설계를 위한 패턴과 원리 - 3.리팩토링을 통한 진보 8부]

http://aeternum.egloos.com/2473500[유연한 설계를 위한 패턴과 원리 - 4.잃어버린 시간을 찾아서 1부]

http://aeternum.egloos.com/2483783[유연한 설계를 위한 패턴과 원리 - 4.잃어버린 시간을 찾아서 2부]

http://aeternum.egloos.com/2486549[유연한 설계를 위한 패턴과 원리 - 4.잃어버린 시간을 찾아서 3부]

http://aeternum.egloos.com/2490834[유연한 설계를 위한 패턴과 원리 - 4.잃어버린 시간을 찾아서 4부]

http://aeternum.egloos.com/2492445[유연한 설계를 위한 패턴과 원리 - 4.잃어버린 시간을 찾아서 5부]

http://aeternum.egloos.com/2493642[유연한 설계를 위한 패턴과 원리 - 5.시간, 돈, 그리고 분석 패턴 1부]

http://aeternum.egloos.com/2497570[유연한 설계를 위한 패턴과 원리 - 5.시간, 돈, 그리고 분석 패턴 2부]

http://aeternum.egloos.com/2503382[유연한 설계를 위한 패턴과 원리 - 5.시간, 돈, 그리고 분석 패턴 3부]

http://aeternum.egloos.com/2508743[유연한 설계를 위한 패턴과 원리 - 5.시간, 돈, 그리고 분석 패턴 4부]

http://aeternum.egloos.com/2511360[유연한 설계를 위한 패턴과 원리 - 5.시간, 돈, 그리고 분석 패턴 5부[完]]
