

http://evilimp.tistory.com/17[mysql server에 외부접근을 허용하고자 할 때]

http://dev.mysql.com/doc/refman/5.0/en/enum.html[10.4.4. The ENUM Type]

http://phpimpact.wordpress.com/2008/06/12/10-great-articles-for-optimizing-mysql-queries/[10 great articles for optimizing MySQL queries]  
http://lastmind.net/blog/2008/05/mysql-replication.html[MySQL Replication]

 SELECT LAST_INSERT_ID()

http://breakpoint.tistory.com/tag/processlist[프로세스 강제 종료 시키기]

http://dev.mysql.com/doc/refman/5.0/en/numeric-types.html[10.2. Numeric Types]

http://dev.mysql.com/downloads/gui-tools/5.0.html[http://dev.mysql.com/downloads/gui-tools/5.0.html]

날짜형식

DATE_FORMAT(now(),'%Y%m%d%H%i%s')

형식변환

http://blog.paran.com/sputnik/1022191[http://blog.paran.com/sputnik/1022191]

http://truefeel.tistory.com/125[MySQL 쿼리 실시간 모니터링 및 저장하기]

http://bret.appspot.com/entry/how-friendfeed-uses-mysql[http://bret.appspot.com/entry/how-friendfeed-uses-mysql]

http://colus.egloos.com/5104902[프랜드피드는 어떻게 MySQL을 사용해서 스키마 없는 데이터를 저장하나" 요약]

http://yunsunghan.tistory.com/456[Mysql5.1 설치 및 한글설정]

==== Update

http://dev.mysql.com/doc/refman/5.0/en/update.html[http://dev.mysql.com/doc/refman/5.0/en/update.html]

http://www.electrictoolbox.com/article/mysql/cross-table-update/[]http://www.electrictoolbox.com/article/mysql/cross-table-update/[http://www.electrictoolbox.com/article/mysql/cross-table-update/]

==== GUI tool

http://dev.mysql.com/downloads/gui-tools/5.0.html[http://dev.mysql.com/downloads/gui-tools/5.0.html]

==== 날짜

DAYOFWEEK(date)

1 = Sunday, 2 = Monday, 7 = Saturday

select  DAYOFWEEK('2007-01-05');

select DAYOFWEEK(now());

cast(ymd as date)

DATE_FORMAT(date_add(cast(gijun_ymd as date), interval 2-dayofweek(gijun_ymd) day), '%Y%m%d' )

http://jeongsam.net/112[http://jeongsam.net/112]

==== Index

show index from  tb_fund_chart_weekly

alter table 테이블명 add index 인덱스명 (칼럼명);

CREATE INDEX <인덱스명> ON <테이블명> ( 칼럼명1, 칼럼명2, ... );

==== Cache

http://dev.mysql.com/doc/refman/5.1/en/ha-memcached-interfaces-mysqludf.html[]http://dev.mysql.com/doc/refman/5.1/en/ha-memcached-interfaces-mysqludf.html[http://dev.mysql.com/doc/refman/5.1/en/ha-memcached-interfaces-mysqludf.html]

http://planet.mysql.com/entry/?id=26207[http://planet.mysql.com/entry/?id=26207]

===== mysql jdbc

**socketTimeout=60000&connectTimeout=60000**

== Innodb vs Myisam

http://dev.kthcorp.com/2011/06/17/why-we-need-to-use-innodb-on-mysql-vs-myisam-comparison/[http://dev.kthcorp.com/2011/06/17/why-we-need-to-use-innodb-on-mysql-vs-myisam-comparison/]

== Meta table

select * from mysql.userselect * from mysql.dbselect version()select * from mysql.general_logshow variables like 'log_output'  

== replication delay
http://www.mysqlperformanceblog.com/2011/07/29/reasons-for-mysql-replication-lag/  

== load data infile

=== options
http://dev.mysql.com/doc/refman/5.1/en/load-data.html[http://dev.mysql.com/doc/refman/5.1/en/load-data.html]http://dev.mysql.com/doc/refman/5.1/en/mysqlimport.html[http://dev.mysql.com/doc/refman/5.1/en/mysqlimport.html]  

=== performance

=== http://venublog.com/2007/11/07/load-data-infile-performance/[http://venublog.com/2007/11/07/load-data-infile-performance/] : 옵션 조정해서 비교하는 사례
http://www.mysqlperformanceblog.com/2008/07/03/how-to-load-large-files-safely-into-innodb-with-load-data-infile/[http://www.mysqlperformanceblog.com/2008/07/03/how-to-load-large-files-safely-into-innodb-with-load-data-infile/] : perl script이용 chunk 사이즈 조정http://chrisjohnson.blogsite.org/php-and-mysql-data-import-performance/[http://chrisjohnson.blogsite.org/php-and-mysql-data-import-performance/] : Php에서 load data in file의 성능비교  
insert 성능 : http://dev.mysql.com/doc/refman/5.1/en/insert-speed.html[http://dev.mysql.com/doc/refman/5.1/en/insert-speed.html]http://kvz.io/blog/2009/03/31/improve-mysql-insert-performance/[http://kvz.io/blog/2009/03/31/improve-mysql-insert-performance/]  
insert delayed : (myisam에서만 가능) http://chapter31.com/2008/05/22/insert-delayed-with-mysql/[http://chapter31.com/2008/05/22/insert-delayed-with-mysql/]  

=== JDBC에 속성포함 예제

jdbc:mysql://127.0.0.1/test?logger=com.mysql.jdbc.log.Slf4JLogger&logSlowQueries=true&slowQueryThresholdMillis=1500&dumpQueriesOnException=true&explainSlowQueries=true&connectTimeout=1000&socketTimeout=2000  

Column not  found 에러 :  

http://stackoverflow.com/questions/18730805/mysql-select-statement-with-alias-fails-with-column-not-found  

?useOldAliasMetadataBehavior=true  

http://forums.mysql.com/read.php?39,424792,424792 

http://forums.mysql.com/read.php?39,424792,430313#msg-430313  
 
