name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: benelog/obsidian-site@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4

