name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: obsidian-site-action/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: obsidian-site-action
      - name: Build
        run: npm run build -- --source ..
        working-directory: obsidian-site-action
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4

